// <auto-generated />
using System;
using DoughBoysMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoughBoysMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190417012907_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoughBoysMVC.Models.CustomerOrder", b =>
                {
                    b.Property<int>("OrderNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DoughnutType")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("OrderDate");

                    b.Property<bool>("OrderStatus");

                    b.Property<string>("PhoneNo")
                        .IsRequired();

                    b.Property<string>("PickUpDate")
                        .IsRequired();

                    b.Property<int?>("Quantity")
                        .IsRequired();

                    b.HasKey("OrderNo");

                    b.ToTable("CustomerOrders");

                    b.HasData(
                        new
                        {
                            OrderNo = 200,
                            DoughnutType = "Glazed",
                            Email = "email@email.com",
                            FirstName = "Greg",
                            LastName = "M",
                            OrderDate = "4/16/2019",
                            OrderStatus = false,
                            PhoneNo = "1234567890",
                            PickUpDate = "4/19/2019",
                            Quantity = 17
                        },
                        new
                        {
                            OrderNo = 201,
                            DoughnutType = "Cinnamon Sugar",
                            Email = "email@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            OrderDate = "4/16/2019",
                            OrderStatus = false,
                            PhoneNo = "1234567890",
                            PickUpDate = "4/19/2019",
                            Quantity = 29
                        },
                        new
                        {
                            OrderNo = 202,
                            DoughnutType = "Glazed",
                            Email = "email@email.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            OrderDate = "4/16/2019",
                            OrderStatus = false,
                            PhoneNo = "1234567890",
                            PickUpDate = "4/19/2019",
                            Quantity = 75
                        },
                        new
                        {
                            OrderNo = 203,
                            DoughnutType = "Glazed",
                            Email = "email@email.com",
                            FirstName = "James",
                            LastName = "Jameson",
                            OrderDate = "4/16/2019",
                            OrderStatus = false,
                            PhoneNo = "1234567890",
                            PickUpDate = "4/19/2019",
                            Quantity = 99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
